var CARBO_DB = [
  {name:"NDURAZ gel",             categoria:"Gel",      carbo_g:45,   sodio_mg:460,   caffeina_mg:0,   proteine_g:0},
  {name:"NDURAZ caffeina gel",    categoria:"Gel",      carbo_g:45,   sodio_mg:460,   caffeina_mg:65,  proteine_g:0},
  {name:"4endurance gel",         categoria:"Gel",      carbo_g:30,   sodio_mg:100,   caffeina_mg:0,   proteine_g:0},
  {name:"VitaStrong gel",         categoria:"Gel",      carbo_g:40,   sodio_mg:12,    caffeina_mg:0,   proteine_g:0},
  {name:"VitaStrong gel caffeina",categoria:"Gel",      carbo_g:37,   sodio_mg:12,    caffeina_mg:100, proteine_g:0},
  {name:"Enervit Carbo gel C2:1", categoria:"Gel",      carbo_g:40,   sodio_mg:0,     caffeina_mg:0,   proteine_g:0},
  {name:"Prozis gel",             categoria:"Gel",      carbo_g:29.5, sodio_mg:0,     caffeina_mg:0,   proteine_g:0},
  {name:"SIS Beta Fuel",          categoria:"Gel",      carbo_g:40,   sodio_mg:12,    caffeina_mg:0,   proteine_g:0},
  {name:"Volchem ENERGEN",        categoria:"Gel",      carbo_g:21,   sodio_mg:43,    caffeina_mg:0,   proteine_g:0},
  {name:"Haribo 100g",            categoria:"Snack",    carbo_g:79,   sodio_mg:20,    caffeina_mg:0,   proteine_g:5.7},
  {name:"Haribo singolo (5.5g)",  categoria:"Snack",    carbo_g:4.3,  sodio_mg:1.1,   caffeina_mg:0,   proteine_g:0.3},
  {name:"CliffBar",               categoria:"Barretta", carbo_g:35,   sodio_mg:228,   caffeina_mg:0,   proteine_g:11},
  {name:"Enervit barretta cocoa", categoria:"Barretta", carbo_g:32,   sodio_mg:56,    caffeina_mg:0,   proteine_g:11.4},
  {name:"Naak Waffle",            categoria:"Barretta", carbo_g:16,   sodio_mg:168,   caffeina_mg:0,   proteine_g:3.3},
  {name:"Barretta Nature Valley caramello salato", categoria:"Barretta", carbo_g:10.5, sodio_mg:140, caffeina_mg:0, proteine_g:10.4},
  {name:"Barretta VitaStrong protein", categoria:"Barretta", carbo_g:11, sodio_mg:24, caffeina_mg:0,  proteine_g:14},
  {name:"Enervit Carbo Bar C2:1PRO",   categoria:"Barretta", carbo_g:33.3, sodio_mg:7.2, caffeina_mg:0, proteine_g:2},
  {name:"Pastiglie Nduranz Zero Drink",categoria:"Sali",     carbo_g:0,    sodio_mg:300,   caffeina_mg:0,   proteine_g:0},
  {name:"Sali capsule decathlon", categoria:"Sali",     carbo_g:0,    sodio_mg:118,   caffeina_mg:0,   proteine_g:0},
  {name:"Sali capsule Enervit",   categoria:"Sali",     carbo_g:0,    sodio_mg:150,   caffeina_mg:0,   proteine_g:0},
  {name:"Capsula caffeina",       categoria:"Caffeina", carbo_g:0,    sodio_mg:0,     caffeina_mg:200, proteine_g:0},
  {name:"Flask 60g malto+frutt",  categoria:"Flask",    carbo_g:60,   sodio_mg:0,     caffeina_mg:0,   proteine_g:0},
  {name:"Flask 70g malto+frutt",  categoria:"Flask",    carbo_g:70,   sodio_mg:0,     caffeina_mg:0,   proteine_g:0},
  {name:"Flask 75g malto+frutt",  categoria:"Flask",    carbo_g:75,   sodio_mg:0,     caffeina_mg:0,   proteine_g:0},
  {name:"Flask 80g malto+frutt",  categoria:"Flask",    carbo_g:80,   sodio_mg:0,     caffeina_mg:0,   proteine_g:0},
  {name:"Flask 90g malto+frutt",  categoria:"Flask",    carbo_g:90,   sodio_mg:0,     caffeina_mg:0,   proteine_g:0},
  {name:"NDURAZ Drink Mix 100g",  categoria:"Drink Mix",carbo_g:93.8, sodio_mg:304,   caffeina_mg:0,   proteine_g:0},
  {name:"NDURAZ Drink Mix 45g",   categoria:"Drink Mix",carbo_g:45,   sodio_mg:460,   caffeina_mg:0,   proteine_g:0},
  {name:"NDURAZ Drink Mix 96g",   categoria:"Drink Mix",carbo_g:90,   sodio_mg:291.8, caffeina_mg:0,   proteine_g:0},
  {name:"NDURAZ NRGY drink bustina",categoria:"Drink Mix",carbo_g:45, sodio_mg:296,   caffeina_mg:0,   proteine_g:0},
  {name:"Cetilar Race Carb Caf 80g",categoria:"Drink Mix",carbo_g:76.5,sodio_mg:4,   caffeina_mg:150, proteine_g:0},
  {name:"Coca cola bicchiere",    categoria:"Bevanda",  carbo_g:15.9, sodio_mg:0,     caffeina_mg:12,  proteine_g:0},
  {name:"Coca cola lattina 33cl", categoria:"Bevanda",  carbo_g:35,   sodio_mg:0,     caffeina_mg:32,  proteine_g:0}
];
