baseURL = "/"
languageCode = "en-us"
title = "Gabriele Orazi"
theme = "hugo-theme-cactus"
copyright = "Gabriele Orazi" # cactus will use title if copyright is not set
# googleAnalytics = "UA-1234-5"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# summaryLength = 2

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1

    [languages.en.params]
      description = "Cybersecurity PostDoc in SPRITZ Group (UniPd). Strongly unprofessional climber, cyclist and trail runner."

    [[languages.en.menu.main]]
      name = "Short Bio"
      url = "/shortbio"
      weight = 2

    [[languages.en.menu.main]]
      name = "Research"
      url = "/publications"
      weight = 3

    [[languages.en.menu.main]]
      name = "Teaching"
      url = "/teaching"
      weight = 4

    [[languages.en.menu.main]]
      name = "Suggestions"
      url = "/suggestions"
      weight = 7

    [[languages.en.menu.main]]
      name = "About"
      url = "/about"
      weight = 8

    [[languages.en.menu.coach]]
      name = "Home"
      url = "/coach/"
      weight = 1

    [[languages.en.menu.coach]]
      name = "Carbo Calc"
      url = "/coach/carbo/"
      weight = 2

  [languages.it]
    languageName = "Italiano"
    languageCode = "it-it"
    weight = 2

    [languages.it.params]
      description = "PostDoc in Cybersecurity nel gruppo SPRITZ (UniPd). Scalatore, ciclista e trail runner molto poco professionista."

    [[languages.it.menu.main]]
      name = "Bio Breve"
      url = "/it/shortbio"
      weight = 2

    [[languages.it.menu.main]]
      name = "Ricerca"
      url = "/it/publications"
      weight = 3

    [[languages.it.menu.main]]
      name = "Didattica"
      url = "/it/teaching"
      weight = 4

    [[languages.it.menu.main]]
      name = "Consigli"
      url = "/it/suggestions"
      weight = 7

    [[languages.it.menu.main]]
      name = "Chi sono"
      url = "/it/about"
      weight = 8

    [[languages.it.menu.coach]]
      name = "Home"
      url = "/it/coach/"
      weight = 1

    [[languages.it.menu.coach]]
      name = "Calcola Carbo"
      url = "/it/coach/carbo/"
      weight = 2

[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2

[params]

  colortheme = "dark" # dark, light, white, or classic
  css = ["css/custom.css", "css/coach.css"] # here path of css custom file
  rss = false # generate rss feed. default value is false
  # googleAnalyticsAsync = false # use asynchronous tracking. Synchronous tracking by default

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "email"
    link = "gabriele.orazi@unipd.com"  # no need for "mailto:" in the head

  [[params.social]]
    name = "scholar"
    link = "https://scholar.google.com/citations?user=u30gQ60AAAAJ&hl=it"

  [[params.social]]
    name = "github"
    link = "https://github.com/goemon07"

#  [[params.social]]
#    name = "telegram"
#    link = "https://t.me/goemon07"

#  [[params.social]]
#    name = "twitter"
#    link = "https://twitter.com/_goemon07"

#  [[params.social]]
#    name = "bluesky"
#   link = "https://bsky.app/profile/gorazi.bsky.social"

  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/gabriele-orazi/"

#  [[params.social]]
#    name = "strava"
#   link = "https://www.strava.com/athletes/39260108"

[[params.office]]
    department = "Department of Mathematics “Tullio Levi-Civita”"
    office = "2CD8"
    link = "https://www.google.it/maps/search/dipartimento+matematica+padova/@45.4083047,11.8743574,16z"
