baseURL = "/"
languageCode = "en-us"
title = "Gabriele Orazi"
theme = "hugo-theme-cactus"
copyright = "Gabriele Orazi" # cactus will use title if copyright is not set
disqusShortname = "goemon" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Teaching"
url = "/teaching"
weight = 2

[[menu.main]]
name = "Publications"
url = "/publications"
weight = 3

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 4

[[menu.main]]
name = "Readings"
url = "/readings"
weight = 5

[[menu.main]]
name = "About"
url = "/about"
weight = 6

[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2

[params]

  colortheme = "dark" # dark, light, white, or classic
  css = ["css/custom.css"] # here path of css custom file
  rss = false # generate rss feed. default value is false
  googleAnalyticsAsync = false # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "I received my double Master's Degree in Computer Science from the [University of Trento](https://offertaformativa.unitn.it/en/lm/computer-science/cyber-security) and the [University of Turku](https://www.utu.fi/en/study-at-utu/masters-degree-programme-in-information-and-communication-technology-cyber-security), with Cyber Security curriculum in 2020. After two short work experiences as DevSecOps, I joined the University of Padua as a research fellow in the [SPRITZ Security and Privacy Research Group](https://spritz.math.unipd.it/), under the supervision of [Prof. Mauro Conti](https://www.math.unipd.it/~conti/index.html). I am currently a Ph.D. Student in [Brain, Mind and Computer Science (BMCS)](http://hit.psy.unipd.it/BMCS), studying malware detection and privacy preserving methods applied to digital documents. I am also working with [FDM Business Services](https://fdmservices.it/), which is the company that supports my high apprenticeship program and where I try to convey my research interests. I am a GNU/Linux enthusiast, and in my spare time, I enjoy playing CTFs. If I'm away from the keyboard, you can find me rock climbing or trail running in the mountains."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/goemon07" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "email"
    link = "gabriele.orazi@phd.unipd.com"  # no need for "mailto:" in the head

  [[params.social]]
    name = "scholar"
    link = "https://scholar.google.com/citations?user=u30gQ60AAAAJ&hl=it"

  [[params.social]]
    name = "github"
    link = "https://github.com/goemon07"

#  [[params.social]]
#    name = "telegram"
#    link = "https://t.me/goemon07"

  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/_goemon07"

  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/gabriele-orazi/"

[[params.office]]
    department = "Department of Mathematics “Tullio Levi-Civita”"
    office = "7D3 (ex 731)"
